### ISSUE TITLE
Dockerfile build broken: Missing input file 'tgtermes.sty'

### ISSUE THREAD

**Issue by robske110** [certbot/website#754]
With the current Dockerfile docker-compose up fails at build step 17 (gulp build) with the following error.
```
#21 12.95 WARNING: conf value "epub_copyright" (or "copyright")should not be empty for EPUB3
#21 38.23 Rc files read:
#21 38.23   /etc/LatexMk
#21 38.23   ./latexmkrc
#21 38.23 Latexmk: This is Latexmk, John Collins, 29 September 2020, version: 4.70b.
#21 38.24 Rule 'pdflatex': The following rules & subrules became out-of-date:
#21 38.24       'pdflatex'
#21 38.24 ------------
#21 38.24 Run number 1 of rule 'pdflatex'
#21 38.24 ------------
#21 38.24 ------------
#21 38.24 Running 'pdflatex   -recorder  "Certbot.tex"'
#21 38.24 ------------
#21 38.38 Latexmk: Missing input file: 'tgtermes.sty' from line
#21 38.38   '! LaTeX Error: File `tgtermes.sty' not found.'
#21 38.39 Collected error summary (may duplicate other messages):
#21 38.39   pdflatex: Command for 'pdflatex' gave return code 1
#21 38.39       Refer to 'Certbot.log' for details
#21 38.39 Latexmk: Use the -f option to force complete processing,
#21 38.39  unless error was exceeding maximum runs, or warnings treated as errors.
#21 38.39 make[1]: *** [Makefile:29: Certbot.pdf] Error 12
#21 38.39 make: *** [Makefile:117: latexpdf] Error 2
#21 38.40 [17:03:50] 'docs_make' errored after 37 s
#21 38.40 [17:03:50] Error: exited with error code: 2
#21 38.40     at ChildProcess.onexit (/opt/certbot/node_modules/end-of-stream/index.js:40:36)
#21 38.40     at emitTwo (events.js:126:13)
#21 38.40     at ChildProcess.emit (events.js:214:7)
#21 38.40     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
#21 38.40 [17:03:50] 'docs:install' errored after 37 s
#21 38.40 [17:03:50] 'build' errored after 37 s
```

**Comment by alexzorin** [comment]
Hi @robske110,

Thank you for looking at this.

For some context: the current Certbot website has been recently migrated to a content management system which is separate to what is found in this repo. In my understanding, this repo is no longer relevant or maintained, except for the contents of `hosting_providers.json`.

I'm not sure at the moment what's going to happen to the repo, I'll try find out.

**Comment by alexzorin** [comment]
Closing because this repo no longer contains a Dockerfile.
